version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://tolksnrdportfolio --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no